package ProductionControlModule;


/**
* ProductionControlModule/_IProductionControlStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle des machines de production
public class _IProductionControlStub extends org.omg.CORBA.portable.ObjectImpl implements ProductionControlModule.IProductionControl
{


  // Enregistrer une machine auprès du contrôleur
  public boolean registerMachine (String machineId, String machineType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registerMachine", true);
                $out.write_string (machineId);
                $out.write_string (machineType);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registerMachine (machineId, machineType        );
            } finally {
                _releaseReply ($in);
            }
  } // registerMachine


  // Notifier le contrôleur d'une panne
  public String notifyFailure (String machineId, String errorType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notifyFailure", true);
                $out.write_string (machineId);
                $out.write_string (errorType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return notifyFailure (machineId, errorType        );
            } finally {
                _releaseReply ($in);
            }
  } // notifyFailure


  // Demander le démarrage de la production
  public boolean requestProductionStart (String machineId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("requestProductionStart", true);
                $out.write_string (machineId);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return requestProductionStart (machineId        );
            } finally {
                _releaseReply ($in);
            }
  } // requestProductionStart


  // Demander l'arrêt de la production
  public boolean requestProductionStop (String machineId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("requestProductionStop", true);
                $out.write_string (machineId);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return requestProductionStop (machineId        );
            } finally {
                _releaseReply ($in);
            }
  } // requestProductionStop


  // Notifier d'une alerte de stockage (vide ou plein)
  public void notifyStorageAlert (String zoneId, int level)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("notifyStorageAlert", true);
                $out.write_string (zoneId);
                $out.write_long (level);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                notifyStorageAlert (zoneId, level        );
            } finally {
                _releaseReply ($in);
            }
  } // notifyStorageAlert


  // Obtenir le statut d'une machine
  public String getMachineStatus (String machineId)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMachineStatus", true);
                $out.write_string (machineId);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getMachineStatus (machineId        );
            } finally {
                _releaseReply ($in);
            }
  } // getMachineStatus

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProductionControlModule/IProductionControl:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IProductionControlStub
