package ProductionControlModule;


/**
* ProductionControlModule/IProductionControlHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle des machines de production
abstract public class IProductionControlHelper
{
  private static String  _id = "IDL:ProductionControlModule/IProductionControl:1.0";

  public static void insert (org.omg.CORBA.Any a, ProductionControlModule.IProductionControl that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ProductionControlModule.IProductionControl extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ProductionControlModule.IProductionControlHelper.id (), "IProductionControl");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ProductionControlModule.IProductionControl read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IProductionControlStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ProductionControlModule.IProductionControl value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ProductionControlModule.IProductionControl narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProductionControlModule.IProductionControl)
      return (ProductionControlModule.IProductionControl)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProductionControlModule._IProductionControlStub stub = new ProductionControlModule._IProductionControlStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ProductionControlModule.IProductionControl unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ProductionControlModule.IProductionControl)
      return (ProductionControlModule.IProductionControl)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ProductionControlModule._IProductionControlStub stub = new ProductionControlModule._IProductionControlStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
