package ProductionControlModule;


/**
* ProductionControlModule/IProductionControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle des machines de production
public interface IProductionControlOperations 
{

  // Enregistrer une machine auprès du contrôleur
  boolean registerMachine (String machineId, String machineType);

  // Notifier le contrôleur d'une panne
  String notifyFailure (String machineId, String errorType);

  // Demander le démarrage de la production
  boolean requestProductionStart (String machineId);

  // Demander l'arrêt de la production
  boolean requestProductionStop (String machineId);

  // Notifier d'une alerte de stockage (vide ou plein)
  void notifyStorageAlert (String zoneId, int level);

  // Obtenir le statut d'une machine
  String getMachineStatus (String machineId);
} // interface IProductionControlOperations
