package ProductionControlModule;


/**
* ProductionControlModule/IProductionControl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle des machines de production
public interface IProductionControl extends IProductionControlOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IProductionControl
