package ProductionControlModule;


/**
* ProductionControlModule/IProductionControlPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle des machines de production
public abstract class IProductionControlPOA extends org.omg.PortableServer.Servant
 implements ProductionControlModule.IProductionControlOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerMachine", new java.lang.Integer (0));
    _methods.put ("notifyFailure", new java.lang.Integer (1));
    _methods.put ("requestProductionStart", new java.lang.Integer (2));
    _methods.put ("requestProductionStop", new java.lang.Integer (3));
    _methods.put ("notifyStorageAlert", new java.lang.Integer (4));
    _methods.put ("getMachineStatus", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Enregistrer une machine auprès du contrôleur
       case 0:  // ProductionControlModule/IProductionControl/registerMachine
       {
         String machineId = in.read_string ();
         String machineType = in.read_string ();
         boolean $result = false;
         $result = this.registerMachine (machineId, machineType);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Notifier le contrôleur d'une panne
       case 1:  // ProductionControlModule/IProductionControl/notifyFailure
       {
         String machineId = in.read_string ();
         String errorType = in.read_string ();
         String $result = null;
         $result = this.notifyFailure (machineId, errorType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // Demander le démarrage de la production
       case 2:  // ProductionControlModule/IProductionControl/requestProductionStart
       {
         String machineId = in.read_string ();
         boolean $result = false;
         $result = this.requestProductionStart (machineId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Demander l'arrêt de la production
       case 3:  // ProductionControlModule/IProductionControl/requestProductionStop
       {
         String machineId = in.read_string ();
         boolean $result = false;
         $result = this.requestProductionStop (machineId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Notifier d'une alerte de stockage (vide ou plein)
       case 4:  // ProductionControlModule/IProductionControl/notifyStorageAlert
       {
         String zoneId = in.read_string ();
         int level = in.read_long ();
         this.notifyStorageAlert (zoneId, level);
         out = $rh.createReply();
         break;
       }


  // Obtenir le statut d'une machine
       case 5:  // ProductionControlModule/IProductionControl/getMachineStatus
       {
         String machineId = in.read_string ();
         String $result = null;
         $result = this.getMachineStatus (machineId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProductionControlModule/IProductionControl:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IProductionControl _this() 
  {
    return IProductionControlHelper.narrow(
    super._this_object());
  }

  public IProductionControl _this(org.omg.CORBA.ORB orb) 
  {
    return IProductionControlHelper.narrow(
    super._this_object(orb));
  }


} // class IProductionControlPOA
