package ProductionControlModule;

/**
* ProductionControlModule/IProductionControlHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle des machines de production
public final class IProductionControlHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControlModule.IProductionControl value = null;

  public IProductionControlHolder ()
  {
  }

  public IProductionControlHolder (ProductionControlModule.IProductionControl initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControlModule.IProductionControlHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControlModule.IProductionControlHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControlModule.IProductionControlHelper.type ();
  }

}
