package ProductionControlModule;

/**
* ProductionControlModule/IStationControlHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle de la station d'assemblage
public final class IStationControlHolder implements org.omg.CORBA.portable.Streamable
{
  public ProductionControlModule.IStationControl value = null;

  public IStationControlHolder ()
  {
  }

  public IStationControlHolder (ProductionControlModule.IStationControl initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ProductionControlModule.IStationControlHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ProductionControlModule.IStationControlHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ProductionControlModule.IStationControlHelper.type ();
  }

}
