package ProductionControlModule;


/**
* ProductionControlModule/IStationControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle de la station d'assemblage
public interface IStationControlOperations 
{

  // Enregistrer une station d'assemblage
  boolean registerAssemblyStation (String stationId);

  // Notifier d'un problème de qualité
  void notifyQualityIssue (String details);

  // Demander une maintenance
  boolean requestMaintenance (String machineId);

  // Obtenir les commandes de production
  String getProductionCommand (String stationId);
} // interface IStationControlOperations
