package ProductionControlModule;


/**
* ProductionControlModule/IStationControl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle de la station d'assemblage
public interface IStationControl extends IStationControlOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IStationControl
