package ProductionControlModule;


/**
* ProductionControlModule/IStationControlPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from main/idl/ProductionControl.idl
* Wednesday, December 10, 2025 4:34:05 PM WAT
*/


// Interface pour le contrôle de la station d'assemblage
public abstract class IStationControlPOA extends org.omg.PortableServer.Servant
 implements ProductionControlModule.IStationControlOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registerAssemblyStation", new java.lang.Integer (0));
    _methods.put ("notifyQualityIssue", new java.lang.Integer (1));
    _methods.put ("requestMaintenance", new java.lang.Integer (2));
    _methods.put ("getProductionCommand", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Enregistrer une station d'assemblage
       case 0:  // ProductionControlModule/IStationControl/registerAssemblyStation
       {
         String stationId = in.read_string ();
         boolean $result = false;
         $result = this.registerAssemblyStation (stationId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Notifier d'un problème de qualité
       case 1:  // ProductionControlModule/IStationControl/notifyQualityIssue
       {
         String details = in.read_string ();
         this.notifyQualityIssue (details);
         out = $rh.createReply();
         break;
       }


  // Demander une maintenance
       case 2:  // ProductionControlModule/IStationControl/requestMaintenance
       {
         String machineId = in.read_string ();
         boolean $result = false;
         $result = this.requestMaintenance (machineId);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  // Obtenir les commandes de production
       case 3:  // ProductionControlModule/IStationControl/getProductionCommand
       {
         String stationId = in.read_string ();
         String $result = null;
         $result = this.getProductionCommand (stationId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ProductionControlModule/IStationControl:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public IStationControl _this() 
  {
    return IStationControlHelper.narrow(
    super._this_object());
  }

  public IStationControl _this(org.omg.CORBA.ORB orb) 
  {
    return IStationControlHelper.narrow(
    super._this_object(orb));
  }


} // class IStationControlPOA
